# Generated by Django 4.2.27 on 2026-01-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('player_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='player_name', null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('opp', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('is_home', models.SmallIntegerField(blank=True, null=True)),
                ('algo_score_goal', models.FloatField(blank=True, null=True)),
                ('algo_score_shot', models.FloatField(blank=True, null=True)),
                ('python_prob', models.FloatField(blank=True, null=True)),
                ('python_vol', models.FloatField(blank=True, null=True)),
                ('result_goal', models.TextField(blank=True, null=True)),
                ('result_shot', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_lake',
                'ordering': ['-ts', 'name'],
                'managed': True,
            },
        ),
    ]
