# Generated by Django 4.2.27 on 2026-01-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'managed': False, 'ordering': ['-ts', 'name']},
        ),
    ]
