# Generated by Django 4.2.27 on 2026-01-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'ordering': ['-ts', 'name']},
        ),
    ]
