# Generated by Django 4.2.27 on 2026-01-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='data_lake',
        ),
    ]
