# Generated by Django 4.2.27 on 2026-01-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
